import { useState } from 'react';
import {
  Modal,
  Button,
  Divider,
  Icon,
  Message
} from "semantic-ui-react";

/**
 * Where the Donate button leads.
 *
 * Patreon is still a placeholder. An empty string renders that button disabled
 * rather than linking somewhere wrong - this modal used to point at the upstream
 * OpenMHz project's accounts, which would now be sending this site's supporters
 * to somebody else. Fill it in and the button lights up.
 */
const BUY_ME_A_COFFEE_URL = "https://www.buymeacoffee.com/hamrecorder";
const PATREON_URL = "";

// Buy Me a Coffee's own button, generated by their button-api. Served from
// their CDN rather than baked in, which is how they intend it to be used - the
// tradeoff being that the image does not render if a visitor blocks that host,
// hence the alt text saying where the link goes.
const BMC_BUTTON_IMAGE =
  "https://img.buymeacoffee.com/button-api/?text=Buy me a coffee&emoji=&slug=hamrecorder" +
  "&button_colour=FFDD00&font_colour=000000&font_family=Cookie&outline_colour=000000" +
  "&coffee_colour=ffffff";

function SupportModal(props) {

  const [open, setOpen] = useState(false);
  const siteName = process.env.REACT_APP_SITE_NAME;

  /** A donation link, or a disabled button while the account is being set up. */
  const DonateButton = ({ url, icon, label }) => (
    url
      ? <a href={url}><Button><Icon name={icon} />{label}</Button></a>
      : <Button disabled title="Coming soon"><Icon name={icon} />{label}</Button>
  );

  return (
    <Modal open={open} onClose={() => setOpen(false)} onOpen={() => setOpen(true)} trigger={props.trigger} size='tiny' >
      <Modal.Header>Support {siteName}</Modal.Header>
      <Modal.Content image>
        <Icon size='massive' name="coffee" />
        <Modal.Description>
          <p>If {siteName} brings you joy, think about becoming a supporter! It will cover hosting costs.</p>

          <Message info>
            <Message.Header>Supporters get transcription and search</Message.Header>
            <p>
              Every transmission is transcribed, and the archive becomes
              searchable by what was actually said - so you can find the
              transmission you are after without listening through the whole day.
            </p>
          </Message>

          <Divider horizontal>Donate</Divider>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75em', flexWrap: 'wrap' }}>
            <a href={BUY_ME_A_COFFEE_URL} target="_blank" rel="noopener noreferrer">
              <img
                src={BMC_BUTTON_IMAGE}
                alt={`Buy ${siteName} a coffee`}
                style={{ height: '40px', width: 'auto', display: 'block' }}
              />
            </a>
            <DonateButton url={PATREON_URL} icon="patreon" label="Patreon" />
          </div>

        </Modal.Description>

      </Modal.Content>
      <Modal.Actions>
        <Button onClick={() => setOpen(false)} >
          Done
        </Button>
      </Modal.Actions>
    </Modal>

  )

}

export default SupportModal;
